### ISSUE TITLE
bug - peers list, not single value

### ISSUE THREAD

**Issue by JarbasAl** [JarbasHiveMind/HiveMind-core#19]
not sure on trigger condition, but this is now handled

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 328, in _invoke_callbacks
    callback(self)
  File "/home/mycroft/.local/lib/python3.8/site-packages/pyee/_executor.py", line 60, in _callback
    self.emit('error', exc)
  File "/home/mycroft/.local/lib/python3.8/site-packages/pyee/_base.py", line 111, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/home/mycroft/.local/lib/python3.8/site-packages/pyee/_base.py", line 83, in _emit_handle_potential_error
    raise error
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/mycroft/.local/lib/python3.8/site-packages/jarbas_hive_mind/master/__init__.py", line 415, in handle_outgoing_mycroft
    if peer and peer in self.clients:
TypeError: unhashable type: 'list
```

https://github.com/JarbasHiveMind/HiveMind-core/commit/9b68de95af869677800435237c6f68081ae64542

**Comment by JarbasAl** [comment]
reported at https://github.com/JarbasHiveMind/skill-hivemind/issues/4
