### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by builderjer** [JarbasHiveMind/HiveMind-core#34]
Not sure where else to ask this other than maybe a chatroom, but I'll start here.

I have a Mycroft instance running on an OpenSuse server, I cloned this repository according to your directions and the HiveMind-core seems to be running correctly also.

My issue is connecting to the core from a satellite.  I have changed the credentials accordingly, but when I run either the Hive cli, or the Hive voice, I get the same error.

TypeError: __init__() got multiple values for argument 'crypto_key'

Any ideas?

**Comment by ChanceNCounter** [comment]
How are you running the satellites? Have you filled out their config files, or are you passing credentials via the cli? (Just wanna figure out which way's bugged)

**Comment by JarbasAl** [comment]
try using the pip packages, i need to take some more care with github, but github is essentially always WIP and in between versions, so i might break things.... its safest to use pinned versions from pip

either way thanks for the heads up, i need to do a general cleanup of the packages and get them in sync, eg, some satellites depend on older versions of hivemind-core

**Comment by builderjer** [comment]
I have tried changing the config files, and running the config from the cli.  I have tried the git repositories and the pip installations.  They both give the same error.

My test satellite is my laptop running manjaro

**Comment by builderjer** [comment]
I'm looking again at the instructions.  When adding keys, do I do a separate key for each device? Or do I change just the single entry and connect the satellites to that key and crypt?

**Comment by builderjer** [comment]
It was mentioned in the chat that I may need to be using 16 characters for my access_key and crypto_key.  I tried that and ended with the same errors.

On my server:
`(venv) jbrodie@ziggyhost:~/Mycroft/HiveMind-core> python examples/mycroft_master.py 
2021-02-01 07:23:32.771 - OVOS - jarbas_hive_mind.master:start_announcing:176 - INFO - Registering zeroconf:HiveMind-websocket wss://192.168.0.252:5678
2021-02-01 07:23:32.784 - OVOS - jarbas_hive_mind.discovery.ssdp:register:108 - INFO - Registering upnp:HiveMind-websocket (http://192.168.0.252:8088/device.xml)
2021-02-01 07:23:32.794 - OVOS - jarbas_hive_mind:secure_listen:201 - INFO - HiveMind Listening: wss://0.0.0.0:5678
2021-02-01 07:25:33.286 - OVOS - jarbas_hive_mind.master:unregister_client:273 - INFO - deregistering client: tcp4:192.168.0.191:40318
2021-02-01 07:25:33.292 - OVOS - jarbas_hive_mind.master:connectionLost:116 - INFO - WebSocket connection lost: [Failure instance: Traceback: <class 'OpenSSL.SSL.Error'>: [('SSL routines', 'ssl3_get_record', 'http request')]
/home/jbrodie/Mycroft/HiveMind-core/venv/lib/python3.7/site-packages/Twisted-20.3.0-py3.7-linux-x86_64.egg/twisted/internet/posixbase.py:614:_doReadOrWrite
/home/jbrodie/Mycroft/HiveMind-core/venv/lib/python3.7/site-packages/Twisted-20.3.0-py3.7-linux-x86_64.egg/twisted/internet/tcp.py:243:doRead
/home/jbrodie/Mycroft/HiveMind-core/venv/lib/python3.7/site-packages/Twisted-20.3.0-py3.7-linux-x86_64.egg/twisted/internet/tcp.py:249:_dataReceived
/home/jbrodie/Mycroft/HiveMind-core/venv/lib/python3.7/site-packages/Twisted-20.3.0-py3.7-linux-x86_64.egg/twisted/protocols/tls.py:315:dataReceived
--- <exception caught here> ---
/home/jbrodie/Mycroft/HiveMind-core/venv/lib/python3.7/site-packages/Twisted-20.3.0-py3.7-linux-x86_64.egg/twisted/protocols/tls.py:235:_checkHandshakeStatus
/home/jbrodie/Mycroft/HiveMind-core/venv/lib/python3.7/site-packages/pyOpenSSL-20.0.1-py3.7.egg/OpenSSL/SSL.py:1828:do_handshake
/home/jbrodie/Mycroft/HiveMind-core/venv/lib/python3.7/site-packages/pyOpenSSL-20.0.1-py3.7.egg/OpenSSL/SSL.py:1566:_raise_ssl_error
/home/jbrodie/Mycroft/HiveMind-core/venv/lib/python3.7/site-packages/pyOpenSSL-20.0.1-py3.7.egg/OpenSSL/_util.py:57:exception_from_error_queue
]
Unhandled Error
Traceback (most recent call last):
  File "/home/jbrodie/Mycroft/HiveMind-core/venv/lib/python3.7/site-packages/jarbas_hive_mind-0.10.7-py3.7.egg/jarbas_hive_mind/__init__.py", line 222, in listen
    return self.secure_listen(factory=factory, protocol=protocol)
  File "/home/jbrodie/Mycroft/HiveMind-core/venv/lib/python3.7/site-packages/jarbas_hive_mind-0.10.7-py3.7.egg/jarbas_hive_mind/__init__.py", line 203, in secure_listen
    reactor.run()
  File "/home/jbrodie/Mycroft/HiveMind-core/venv/lib/python3.7/site-packages/Twisted-20.3.0-py3.7-linux-x86_64.egg/twisted/internet/base.py", line 1283, in run
    self.mainLoop()
  File "/home/jbrodie/Mycroft/HiveMind-core/venv/lib/python3.7/site-packages/Twisted-20.3.0-py3.7-linux-x86_64.egg/twisted/internet/base.py", line 1292, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/home/jbrodie/Mycroft/HiveMind-core/venv/lib/python3.7/site-packages/Twisted-20.3.0-py3.7-linux-x86_64.egg/twisted/internet/base.py", line 913, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/home/jbrodie/Mycroft/HiveMind-core/venv/lib/python3.7/site-packages/txaio-20.12.1-py3.7.egg/txaio/_common.py", line 136, in _notify_bucket
    notify_one_chunk(calls, self._chunk_size, max(0.0, delay_ms))
  File "/home/jbrodie/Mycroft/HiveMind-core/venv/lib/python3.7/site-packages/txaio-20.12.1-py3.7.egg/txaio/_common.py", line 130, in notify_one_chunk
    raise RuntimeError(msg)
builtins.RuntimeError: Error(s) processing call_later bucket:
'NoneType' object has no attribute 'shutdown'
`
And my client:
`HiveMind-cli --name ZiggyHiveMind --host 192.168.0.252 --access_key Ziggy_Home_Hive! --crypto_key Where_Am_I@_Now?
2021-02-01 07:25:33.218 - OVOS - jarbas_hive_mind:unsafe_connect:76 - INFO - Connecting to ws://192.168.0.252:5678
2021-02-01 07:25:33.218 - OVOS - jarbas_hive_mind:unsafe_connect:77 - WARNING - This listener is unsecured
2021-02-01 07:25:33.248 - OVOS - jarbas_hive_mind.slave.terminal:onClose:36 - WARNING - HiveMind websocket connection closed: connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake)
2021-02-01 07:25:33.249 - OVOS - jarbas_hive_mind.slave.terminal:onClose:50 - ERROR - ConnectionError
2021-02-01 07:25:33.250 - OVOS - jarbas_hive_mind.slave.terminal:clientConnectionLost:213 - ERROR - HiveMind connection lost: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
] .. retrying ..
2021-02-01 07:25:33.250 - OVOS - jarbas_hive_mind.slave.terminal:clientConnectionLost:220 - ERROR - HiveMind connection lost: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
]
`

Maybe you can scroll the error here easier.
