### ISSUE TITLE
"hivemind-client terminal" complains about missing file

### ISSUE THREAD

**Issue by goldyfruit** [JarbasHiveMind/HiveMind-core#65]
```
2023-06-15 23:24:36.708 - OVOS - ovos_bus_client.conf:load_message_bus_config:28 - DEBUG - Loading message bus configs
Traceback (most recent call last):
  File "/home/goldyfruit/Virtualenvs/hivemind/bin/hivemind-client", line 33, in <module>
    sys.exit(load_entry_point('hivemind-bus-client==0.0.3', 'console_scripts', 'hivemind-client')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/goldyfruit/Virtualenvs/hivemind/lib64/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/goldyfruit/Virtualenvs/hivemind/lib64/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/goldyfruit/Virtualenvs/hivemind/lib64/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/goldyfruit/Virtualenvs/hivemind/lib64/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/goldyfruit/Virtualenvs/hivemind/lib64/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/goldyfruit/Virtualenvs/hivemind/lib64/python3.11/site-packages/hivemind_bus_client/scripts.py", line 26, in terminal
    node.connect(FakeBus())
  File "/home/goldyfruit/Virtualenvs/hivemind/lib64/python3.11/site-packages/hivemind_bus_client/client.py", line 97, in connect
    from hivemind_bus_client.protocol import HiveMindSlaveProtocol
  File "/home/goldyfruit/Virtualenvs/hivemind/lib64/python3.11/site-packages/hivemind_bus_client/protocol.py", line 75, in <module>
    class HiveMindSlaveProtocol:
  File "/home/goldyfruit/Virtualenvs/hivemind/lib64/python3.11/site-packages/hivemind_bus_client/protocol.py", line 82, in HiveMindSlaveProtocol
    handshake: HandShake = HandShake(identity.private_key)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/goldyfruit/Virtualenvs/hivemind/lib64/python3.11/site-packages/poorman_handshake/asymmetric/__init__.py", line 17, in __init__
    self.export_private_key(path, binary)
  File "/home/goldyfruit/Virtualenvs/hivemind/lib64/python3.11/site-packages/poorman_handshake/asymmetric/__init__.py", line 31, in export_private_key
    return export_private_key(path, self.private_key, binary)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/goldyfruit/Virtualenvs/hivemind/lib64/python3.11/site-packages/poorman_handshake/asymmetric/utils.py", line 12, in export_private_key
    with open(path, "w") as f:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/goldyfruit/.config/hivemind/unnamed-node.asc'
```

**Comment by goldyfruit** [comment]
`~/.config/hivemind` directory is not automatically created, I had to create it first and then the error was gone.
