### ISSUE TITLE
Default port should be different than the Mycroft message bus

### ISSUE THREAD

**Issue by goldyfruit** [JarbasHiveMind/HiveMind-core#66]
Because both have to run at the same place, they can't have the same port. I think by default, hivemind should be running on a different port than 8081.
```
(hivemind) pi@rpi4b01:~ $ hivemind-core listen 
2023-06-15 23:22:07.445 - HiveMind - hivemind_core.service:on_alive:79 - INFO - HiveMind bus service alive
2023-06-15 23:22:07.448 - HiveMind - hivemind_core.protocol:register_bus_handlers:108 - INFO - registering internal mycroft bus handlers
2023-06-15 23:22:07.450 - HiveMind - hivemind_core.service:on_started:83 - INFO - HiveMind bus service started!
2023-06-15 23:22:07.451 - HiveMind - hivemind_core.service:run:225 - INFO - ws connection started
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/home/pi/.venv/hivemind/lib/python3.9/site-packages/hivemind_core/service.py", line 226, in run
    application.listen(self.port, self.host)
  File "/home/pi/.venv/hivemind/lib/python3.9/site-packages/tornado/web.py", line 2207, in listen
    server.listen(
  File "/home/pi/.venv/hivemind/lib/python3.9/site-packages/tornado/tcpserver.py", line 183, in listen
    sockets = bind_sockets(
  File "/home/pi/.venv/hivemind/lib/python3.9/site-packages/tornado/netutil.py", line 162, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 98] Address already in use
```

**Comment by goldyfruit** [comment]
> default port is 5678 thinking

I have nothing running on this port.

**Comment by JarbasAl** [comment]
fixed

**Comment by goldyfruit** [comment]
Since the commit I got this error:
```
Traceback (most recent call last):
  File "/home/pi/.venv/hivemind/bin/hivemind-core", line 11, in <module>
    load_entry_point('jarbas-hive-mind==0.13.0a1', 'console_scripts', 'hivemind-core')()
  File "/home/pi/.venv/hivemind/lib/python3.9/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/pi/.venv/hivemind/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/pi/.venv/hivemind/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/pi/.venv/hivemind/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/pi/.venv/hivemind/lib/python3.9/site-packages/hivemind_core/scripts.py", line 56, in <module>
    def delete_client(node_id):
  File "/home/pi/.venv/hivemind/lib/python3.9/site-packages/click/decorators.py", line 287, in decorator
    _param_memo(f, ArgumentClass(param_decls, **attrs))
  File "/home/pi/.venv/hivemind/lib/python3.9/site-packages/click/core.py", line 2950, in __init__
    super().__init__(param_decls, required=required, **attrs)
TypeError: __init__() got an unexpected keyword argument 'help'
```

**Comment by JarbasAl** [comment]
try again please

**Comment by goldyfruit** [comment]
All good.

```
(hivemind) pi@rpi4b01:~ $ hivemind-core listen --ssl true 
2023-06-16 12:56:26.574 - HiveMind - hivemind_core.service:on_alive:79 - INFO - HiveMind bus service alive
2023-06-16 12:56:26.577 - HiveMind - hivemind_core.protocol:register_bus_handlers:108 - INFO - registering internal mycroft bus handlers
2023-06-16 12:56:26.579 - HiveMind - hivemind_core.service:on_started:83 - INFO - HiveMind bus service started!
2023-06-16 12:56:26.584 - HiveMind - hivemind_core.service:run:222 - INFO - wss connection started
2023-06-16 12:56:26.588 - HiveMind - hivemind_core.service:on_ready:75 - INFO - HiveMind bus service ready!
```

```
(hivemind) pi@rpi4b01:~ $ ss -plantu | grep 5678
tcp   LISTEN     0      128                  0.0.0.0:5678                 0.0.0.0:*     users:(("hivemind-core",pid=425002,fd=15)) 
```
