### ISSUE TITLE
Handle client deletion by name

### ISSUE THREAD

**Issue by goldyfruit** [JarbasHiveMind/HiveMind-core#68]
When trying to delete a client with its name instead of the ID.
```
Traceback (most recent call last):
  File "/home/goldyfruit/Virtualenvs/hivemind/bin/hivemind-core", line 33, in <module>
    sys.exit(load_entry_point('jarbas-hive-mind==0.13.0a1', 'console_scripts', 'hivemind-core')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/goldyfruit/Virtualenvs/hivemind/lib64/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/goldyfruit/Virtualenvs/hivemind/lib64/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/goldyfruit/Virtualenvs/hivemind/lib64/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/goldyfruit/Virtualenvs/hivemind/lib64/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/goldyfruit/Virtualenvs/hivemind/lib64/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/goldyfruit/Virtualenvs/hivemind/lib64/python3.11/site-packages/hivemind_core/scripts.py", line 59, in delete_client
    if x["client_id"] == int(node_id):
                         ^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'HiveMind-Node-0'
```

**Comment by JarbasAl** [comment]
names are not guaranteed to be unique, they are just friendly names for UI

using the unique identifier is required, not a bug but will add more info the the --help command

**Comment by goldyfruit** [comment]
> names are not guaranteed to be unique, they are just friendly names for UI
> 
> using the unique identifier is required, not a bug but will add more info the the --help command

Maybe just make sure than ID is an integer if not then a message could be displayed to the user like `please use the ID not the name`.

**Comment by JarbasAl** [comment]
last commit should have handled this
